<?php
return [
    [
        'payment_status' => 'completed',
        'total_price' => 59.99,
        'name' => 'Marco Rossi',
        'phone' => '02 1234567',
        'address' => 'Via dei Fiori 10, Milano',
        'notes' => 'Leave at front door.',
    ],
    [
        'payment_status' => 'pending',
        'total_price' => 23.75,
        'name' => 'Francesca Bianchi',
        'phone' => '02 9876543',
        'address' => 'Corso Vittorio Emanuele II, 45, Milano',
        'notes' => 'Ring the bell upon arrival.',
    ],
    [
        'payment_status' => 'failed',
        'total_price' => 0.00,
        'name' => 'Giovanni Romano',
        'phone' => '02 3344556',
        'address' => 'Piazza Duomo, 1, Milano',
        'notes' => 'Contact for a new payment method.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 45.00,
        'name' => 'Alessandra Russo',
        'phone' => '02 8765432',
        'address' => 'Via Dante Alighieri, 20, Milano',
        'notes' => '',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 89.95,
        'name' => 'Luca Ferrari',
        'phone' => '02 1122334',
        'address' => 'Via Montenapoleone, 15, Milano',
        'notes' => 'Call on arrival.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 75.20,
        'name' => 'Sofia Martini',
        'phone' => '02 4455667',
        'address' => 'Corso Buenos Aires, 80, Milano',
        'notes' => 'Please leave in the mailbox if not home.',
    ],
    [
        'payment_status' => 'pending',
        'total_price' => 48.50,
        'name' => 'Matteo Esposito',
        'phone' => '02 7788990',
        'address' => 'Via della Moscova, 25, Milano',
        'notes' => 'Call when outside, gate is tricky.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 65.00,
        'name' => 'Chiara Moretti',
        'phone' => '02 3456789',
        'address' => 'Via Larga, 35, Milano',
        'notes' => '',
    ],
    [
        'payment_status' => 'failed',
        'total_price' => 0.00,
        'name' => 'Lorenzo Conti',
        'phone' => '02 8901234',
        'address' => 'Viale Abruzzi, 30, Milano',
        'notes' => 'Please retry payment.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 55.75,
        'name' => 'Elena Barbieri',
        'phone' => '02 4567890',
        'address' => 'Via Padova, 55, Milano',
        'notes' => 'If not home, leave with neighbor.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 82.99,
        'name' => 'Andrea Colombo',
        'phone' => '02 6789012',
        'address' => 'Corso Magenta, 70, Milano',
        'notes' => 'Special delivery instructions will follow.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 120.50,
        'name' => 'Giulia De Luca',
        'phone' => '02 2345678',
        'address' => 'Piazza San Babila, 10, Milano',
        'notes' => 'Deliver to the main gate security.',
    ],
];