<?php
return [
    [
        'payment_status' => 'completed',
        'total_price' => 59.99,
        'name' => 'John Doe',
        'phone' => '555-1234',
        'address' => '123 Main St, Anytown',
        'notes' => 'Leave at front door.',
    ],
    [
        'payment_status' => 'pending',
        'total_price' => 23.75,
        'name' => 'Jane Smith',
        'phone' => '555-5678',
        'address' => '456 Maple Ave, Elsewhere',
        'notes' => 'Ring the bell upon arrival.',
    ],
    [
        'payment_status' => 'failed',
        'total_price' => 0.00,
        'name' => 'Alex Johnson',
        'phone' => '555-9012',
        'address' => '789 Birch St, Somewhere',
        'notes' => 'Contact for a new payment method.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 45.00,
        'name' => 'Chris Lee',
        'phone' => '555-3456',
        'address' => '101 Oak Rd, Anywhere',
        'notes' => '',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 89.95,
        'name' => 'Pat Kim',
        'phone' => '555-7890',
        'address' => '202 Pine Ct, Nowhere',
        'notes' => 'Call on arrival.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 75.20,
        'name' => 'Morgan Freeman',
        'phone' => '555-1122',
        'address' => '334 Willow Lane, Smalltown',
        'notes' => 'Please leave in the mailbox if not home.',
    ],
    [
        'payment_status' => 'pending',
        'total_price' => 48.50,
        'name' => 'Taylor Swift',
        'phone' => '555-2244',
        'address' => '221B Baker Street, Londontown',
        'notes' => 'Call when outside, gate is tricky.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 65.00,
        'name' => 'Bruce Wayne',
        'phone' => '555-3366',
        'address' => '1007 Mountain Drive, Gotham',
        'notes' => '',
    ],
    [
        'payment_status' => 'failed',
        'total_price' => 0.00,
        'name' => 'Peter Parker',
        'phone' => '555-4488',
        'address' => '20 Ingram Street, Forest Hills',
        'notes' => 'Please retry payment.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 55.75,
        'name' => 'Clark Kent',
        'phone' => '555-5500',
        'address' => '1938 Sullivan Lane, Metropolis',
        'notes' => 'If not home, leave with neighbor.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 82.99,
        'name' => 'Diana Prince',
        'phone' => '555-6622',
        'address' => 'Themyscira Island, Aegean Sea',
        'notes' => 'Special delivery instructions will follow.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 120.50,
        'name' => 'Tony Stark',
        'phone' => '555-7744',
        'address' => '10880 Malibu Point, Malibu',
        'notes' => 'Deliver to the main gate security.',
    ],
];