<?php
return [
    [
        'payment_status' => 'completed',
        'total_price' => 59.99,
        'name' => 'Marco Rossi',
        'phone' => '02 1234567',
        'address' => 'Via dei Fiori 10, Milano',
        'notes' => 'Lasciare di fronte alla porta.',
    ],
    [
        'payment_status' => 'pending',
        'total_price' => 23.75,
        'name' => 'Francesca Bianchi',
        'phone' => '02 9876543',
        'address' => 'Corso Vittorio Emanuele II, 45, Milano',
        'notes' => 'Suonare il campanello.',
    ],
    [
        'payment_status' => 'failed',
        'total_price' => 0.00,
        'name' => 'Giovanni Romano',
        'phone' => '02 3344556',
        'address' => 'Piazza Duomo, 1, Milano',
        'notes' => 'Chiamami per capire come pagare.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 45.00,
        'name' => 'Alessandra Russo',
        'phone' => '02 8765432',
        'address' => 'Via Dante Alighieri, 20, Milano',
        'notes' => 'Attenti al cane.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 89.95,
        'name' => 'Luca Ferrari',
        'phone' => '02 1122334',
        'address' => 'Via Montenapoleone, 15, Milano',
        'notes' => 'Chiamami quando arrivi.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 75.20,
        'name' => 'Sofia Martini',
        'phone' => '02 4455667',
        'address' => 'Corso Buenos Aires, 80, Milano',
        'notes' => 'Lascialo pure in portineria.',
    ],
    [
        'payment_status' => 'pending',
        'total_price' => 48.50,
        'name' => 'Matteo Esposito',
        'phone' => '02 7788990',
        'address' => 'Via della Moscova, 25, Milano',
        'notes' => 'Il campanello non funziona, chiamami.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 65.00,
        'name' => 'Chiara Moretti',
        'phone' => '02 3456789',
        'address' => 'Via Larga, 35, Milano',
        'notes' => 'Non citofonare, Chiamami.',
    ],
    [
        'payment_status' => 'failed',
        'total_price' => 0.00,
        'name' => 'Lorenzo Conti',
        'phone' => '02 8901234',
        'address' => 'Viale Abruzzi, 30, Milano',
        'notes' => 'Pago in contanti alla consegna.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 55.75,
        'name' => 'Elena Barbieri',
        'phone' => '02 4567890',
        'address' => 'Via Padova, 55, Milano',
        'notes' => 'Terzo portone a destra.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 82.99,
        'name' => 'Andrea Colombo',
        'phone' => '02 6789012',
        'address' => 'Corso Magenta, 70, Milano',
        'notes' => 'Mandami un messaggio quando arrivi.',
    ],
    [
        'payment_status' => 'completed',
        'total_price' => 120.50,
        'name' => 'Giulia De Luca',
        'phone' => '02 2345678',
        'address' => 'Piazza San Babila, 10, Milano',
        'notes' => 'Terza scala secondo piano a sinistra.',
    ],
];