<?php
return [

    // Restaurant 1
        [
            'restaurant_id' => 1,
            'name' => 'Pizza Margherita La Dolce Vita',
            'description' => 'Classica Pizza Margherita con mozzarella fresca e basilico.',
            'price' => 9.50, 'visible' => true,
            'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
            'image' => 'margherita-pizza.jpg'
        ],
        [
            'restaurant_id' => 1,
            'name' => 'Pasta alla Carbonara La Dolce Vita',
            'description' => 'La carbonara è un piatto di pasta cremoso, ricco e pieno di sapore, un classico della cucina romana.',
            'price' => 12.00,
            'visible' => true,
            'ingredients' => 'Spaghetti, Uova, Pecorino Romano, Guanciale, Pepe Nero',
            'image' => 'pasta-carbonara.jpg'
        ],
        [
            'restaurant_id' => 1, 
            'name' => 'Tiramisù La Dolce Vita', 
            'description' => 'Classico dessert Italiano al gusto di caffè.', 
            'price' => 6.50, 'visible' => true, 
            'ingredients' => 'Mascarpone, Caffè Espresso, Savoiardi, Cacao', 
            'image' => 'tiramisu.jpg'
        ],
        [
            'restaurant_id' => 1, 
            'name' => 'Gnocchi La Dolce Vita', 
            'description' => 'Gli gnocchi di patate sono un piatto tradizionale italiano costituito da piccole palline di impasto di patate, farina e uova.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Patate, Farina, Uova, Salvia, Burro', 
            'image' => 'gnocchi.jpg'
        ],
        [
            'restaurant_id' => 1, 
            'name' => 'Panna Cotta La Dolce Vita', 
            'description' => 'È un dolce elegante e delicato, amato per la sua semplicità e il suo gusto delizioso.', 
            'price' => 7.00, 
            'visible' => true, 
            'ingredients' => 'Panna Liquida, Zucchero, Vaniglia, Gelatina in fogli', 
            'image' => 'panna-cotta.jpg',
        ],
        [
            'restaurant_id' => 1, 
            'name' => 'Zuppa di Vongole La Dolce Vita', 
            'description' => 'La Zuppa di Vongole è un piatto ricco e confortante, amato per il suo sapore rustico e avvolgente.', 
            'price' => 8.95, 
            'visible' => true,
            'ingredients' => 'Molluschi, Patate, Cipolle, Sedano, Latte, Bacon', 
            'image' => 'clam-chowder.jpg',
        ],
        [
            'restaurant_id' => 1, 
            'name' => 'Pulled Pork Sandwich La Dolce Vita', 
            'description' => 'È un piatto apprezzato per la sua ricchezza di sapore e la sua morbidezza.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Spalla di Maiale, Salsa BBQ, Coleslaw, Pane', 
            'image' => 'pulled-pork-sandwich.jpg',
        ],
        [
            'restaurant_id' => 1,
            'name' => 'Patatine Fritte La Dolce Vita',
            'description' => 'Le patatine fritte sono amate per la loro croccantezza esterna e la morbidezza interna, rendendole un contorno versatile o uno snack da gustare da solo.',
            'price' => 2.99,
            'visible' => true,
            'ingredients' => 'Potate, Sale, Olio Vegetale',
            'image' => 'french-fries.jpg',
        ],
        [
            'restaurant_id' => 1, 
            'name' => 'Cheeseburger La Dolce Vita', 
            'description' => 'Viene apprezzato per il suo sapore succulento, la sua semplicità e la sua versatilità.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Manzo, Formaggio, Lattuga, Pomodoro, Cipolla, Pane', 
            'image' => 'cheeseburger.jpg'
        ],
        [
            'restaurant_id' => 1, 
            'name' => 'BBQ Ribs La Dolce Vita', 
            'description' => 'Sono un piatto apprezzato per la loro bontà e versatilità, e sono una presenza fissa nei menu dei ristoranti barbecue in tutto il mondo.', 
            'price' => 16.50, 
            'visible' => true, 
            'ingredients' => 'Costolette di Maiale, Salsa BBQ, Patate', 
            'image' => 'bbq-ribs.jpg'
        ],
    
        // Restaurant 2
        [
            'restaurant_id' => 2,
            'name' => 'Pizza Margherita del Borgo',
            'description' => 'Classica Pizza Margherita con mozzarella fresca e basilico.',
            'price' => 9.50, 'visible' => true,
            'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
            'image' => 'margherita-pizza.jpg'
        ],
        [
            'restaurant_id' => 2,
            'name' => 'Pasta alla Carbonara del Borgo',
            'description' => 'La carbonara è un piatto di pasta cremoso, ricco e pieno di sapore, un classico della cucina romana.',
            'price' => 12.00,
            'visible' => true,
            'ingredients' => 'Spaghetti, Uova, Pecorino Romano, Guanciale, Pepe Nero',
            'image' => 'pasta-carbonara.jpg'
        ],
        [
            'restaurant_id' => 2, 
            'name' => 'Tiramisù del Borgo', 
            'description' => 'Classico dessert Italiano al gusto di caffè.', 
            'price' => 6.50, 'visible' => true, 
            'ingredients' => 'Mascarpone, Caffè Espresso, Savoiardi, Cacao', 
            'image' => 'tiramisu.jpg'
        ],
        [
            'restaurant_id' => 2, 
            'name' => 'Gnocchi del Borgo', 
            'description' => 'Gli gnocchi di patate sono un piatto tradizionale italiano costituito da piccole palline di impasto di patate, farina e uova.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Patate, Farina, Uova, Salvia, Burro', 
            'image' => 'gnocchi.jpg'
        ],
        [
            'restaurant_id' => 2, 
            'name' => 'Panna Cotta del Borgo', 
            'description' => 'È un dolce elegante e delicato, amato per la sua semplicità e il suo gusto delizioso.', 
            'price' => 7.00, 
            'visible' => true, 
            'ingredients' => 'Panna Liquida, Zucchero, Vaniglia, Gelatina in fogli', 
            'image' => 'panna-cotta.jpg',
        ],
        [
            'restaurant_id' => 2, 
            'name' => 'Sushi Misto del Borgo', 
            'description' => 'È un piatto apprezzato per la sua freschezza, la sua presentazione artistica e la sua varietà di sapori e texture.', 
            'price' => 15.00, 
            'visible' => true, 
            'ingredients' => 'Salmone, Tonno, Cetriolo, Riso, Alghe', 
            'image' => 'sushi-platter.jpg'
        ],
        [
            'restaurant_id' => 2, 
            'name' => 'Ramen del Borgo', 
            'description' => "Molto popolare e amato in Giappone e in tutto il mondo per la sua ricchezza di sapore, la sua versatilità e la sua capacità di riscaldare il corpo e l'anima.", 
            'price' => 13.50, 
            'visible' => true, 
            'ingredients' => 'Brodo di Maiale, Noodle, Maiale, Uova, Cipollotto', 
            'image' => 'ramen.jpg'
        ],
        [
            'restaurant_id' => 2, 
            'name' => 'Katsu Curry del Borgo', 
            'description' => 'È un piatto apprezzato per la combinazione di croccantezza e sapore ricco della carne impanata e della salsa curry.',
            'price' => 9.75,
            'visible' => true, 
            'ingredients' => 'Pollo, Pane Grattugiato, Curry, Riso', 
            'image' => 'katsu-curry.jpg'
        ],
        [
            'restaurant_id' => 2,
            'name' => 'Zuppa di Miso del Borgo', 
            'description' => 'La zuppa di miso è apprezzata per il suo sapore salato e leggermente dolce, nonché per le sue proprietà nutrienti.', 
            'price' => 4.50, 
            'visible' => true, 
            'ingredients' => 'Pasta di Miso, Alghe, Tofu, Cipollotto', 
            'image' => 'miso-soup.jpg'
        ],
        [
            'restaurant_id' => 2, 
            'name' => 'Pollo Teriyaki del Borgo', 
            'description' => 'Amato per il suo sapore appagante e la sua semplicità di preparazione.', 
            'price' => 9.50, 
            'visible' => true, 
            'ingredients' => 'Pollo, Salsa di Soia, Mirin, Zucchero, Sakè', 
            'image' => 'teriyaki-chicken.jpg',
        ],

        // Restaurant 3
        [
            'restaurant_id' => 3,
            'name' => 'Pizza Margherita del Gondoliere',
            'description' => 'Classica Pizza Margherita con mozzarella fresca e basilico.',
            'price' => 9.50, 'visible' => true,
            'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
            'image' => 'margherita-pizza.jpg'
        ],
        [
            'restaurant_id' => 3,
            'name' => 'Pasta alla Carbonara del Gondoliere',
            'description' => 'La carbonara è un piatto di pasta cremoso, ricco e pieno di sapore, un classico della cucina romana.',
            'price' => 12.00,
            'visible' => true,
            'ingredients' => 'Spaghetti, Uova, Pecorino Romano, Guanciale, Pepe Nero',
            'image' => 'pasta-carbonara.jpg'
        ],
        [
            'restaurant_id' => 3, 
            'name' => 'Tiramisù del Gondoliere', 
            'description' => 'Classico dessert Italiano al gusto di caffè.',  
            'price' => 6.50, 'visible' => true, 
            'ingredients' => 'Mascarpone, Caffè Espresso, Savoiardi, Cacao', 
            'image' => 'tiramisu.jpg'
        ],
        [
            'restaurant_id' => 3, 
            'name' => 'Gnocchi del Gondoliere', 
            'description' => 'Gli gnocchi di patate sono un piatto tradizionale italiano costituito da piccole palline di impasto di patate, farina e uova.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Patate, Farina, Uova, Salvia, Burro', 
            'image' => 'gnocchi.jpg'
        ],
        [
            'restaurant_id' => 3, 
            'name' => 'Panna Cotta del Gondoliere', 
            'description' => 'È un dolce elegante e delicato, amato per la sua semplicità e il suo gusto delizioso.', 
            'price' => 7.00, 
            'visible' => true, 
            'ingredients' => 'Panna Liquida, Zucchero, Vaniglia, Gelatina in fogli', 
            'image' => 'panna-cotta.jpg',
        ],
        [
            'restaurant_id' => 3, 
            'name' => 'Pollo Kung Pao del Gondoliere', 
            'description' => ' La combinazione di ingredienti freschi e spezie rende il pollo Kung Pao un piatto molto apprezzato sia in Cina che in molte cucine internazionali.',
            'price' => 8.99,
            'visible' => true, 
            'ingredients' => 'Pollo, Arachidi, Zucchine, Peperoni, Salsa di Soia, Chili', 
            'image' => 'kung-pao-chicken.jpg'
        ],
        [
            'restaurant_id' => 3, 
            'name' => 'Manzo e Broccoli del Gondoliere', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 3, 
            'name' => 'Involtini Primavera del Gondoliere', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 3,
            'name' => 'Anatra alla Pechinese del Gondoliere',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 3,
            'name' => 'Mapo Tofu del Gondoliere',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],

        // Restaurant 4
        [
            'restaurant_id' => 4,
            'name' => 'Pizza Margherita',
            'description' => 'Classica Pizza Margherita con mozzarella fresca e basilico.',
            'price' => 9.50, 'visible' => true,
            'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
            'image' => 'margherita-pizza.jpg'
        ],
        [
            'restaurant_id' => 4,
            'name' => 'Pasta alla Carbonara',
            'description' => 'La carbonara è un piatto di pasta cremoso, ricco e pieno di sapore, un classico della cucina romana.',
            'price' => 12.00,
            'visible' => true,
            'ingredients' => 'Spaghetti, Uova, Pecorino Romano, Guanciale, Pepe Nero',
            'image' => 'pasta-carbonara.jpg'
        ],
        [
            'restaurant_id' => 4, 
            'name' => 'Tiramisu', 
            'description' => 'Classico dessert Italiano al gusto di caffè.', 
            'price' => 6.50, 'visible' => true, 
            'ingredients' => 'Mascarpone, Caffè Espresso, Savoiardi, Cacao', 
            'image' => 'tiramisu.jpg'
        ],
        [
            'restaurant_id' => 4, 
            'name' => 'Gnocchi', 
            'description' => 'Gli gnocchi di patate sono un piatto tradizionale italiano costituito da piccole palline di impasto di patate, farina e uova.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Patate, Farina, Uova, Salvia, Burro', 
            'image' => 'gnocchi.jpg'
        ],
        [
            'restaurant_id' => 4, 
            'name' => 'Panna Cotta', 
            'description' => 'È un dolce elegante e delicato, amato per la sua semplicità e il suo gusto delizioso.', 
            'price' => 7.00, 
            'visible' => true, 
            'ingredients' => 'Panna Liquida, Zucchero, Vaniglia, Gelatina in fogli', 
            'image' => 'panna-cotta.jpg',
        ],
        [
            'restaurant_id' => 4, 
            'name' => 'Tacos Al Pastor', 
            'description' => "È un piatto molto popolare e apprezzato per il suo sapore robusto e piccante, e la sua freschezza grazie all'aggiunta di ananas.", 
            'price' => 9.00, 
            'visible' => true, 
            'ingredients' => 'Maiale, Ananas, Cipolla, Coriandolo, Tortillas di Mais', 
            'image' => 'tacos-al-pastor.jpg'
        ],
        [
            'restaurant_id' => 4, 
            'name' => 'Guacamole', 
            'description' => "Noto per il suo sapore cremoso e fresco, derivato dall'avAnatrado, e per la sua versatilità in cucina.", 
            'price' => 6.50, 
            'visible' => true, 
            'ingredients' => 'AvAnatrado, Cipolle, Pomodori, Lime, Coriandolo', 
            'image' => 'guacamole.jpg'
        ],
        [
            'restaurant_id' => 4, 
            'name' => 'Ceviche', 
            'description' => ' È un piatto leggero e rinfrescante, perfetto per le giornate calde.', 
            'price' => 12.50, 'visible' => true, 
            'ingredients' => 'Pesce, Lime, Cipolle, Coriandolo, Peperoncino', 
            'image' => 'ceviche.jpg',
        ],
        [
            'restaurant_id' => 4, 
            'name' => 'Fajitas', 
            'description' => "Le Fajitas Tandoori offrono un'esplosione di sapori speziati e sono un'opzione deliziosa e unica per un pasto.", 
            'price' => 13.95, 
            'visible' => true, 
            'ingredients' => 'Pollo, Peperoni, Cipolle, Spezie', 
            'image' => 'fajitas.jpg',
        ],
        [
            'restaurant_id' => 4,
            'name' => 'Enchiladas Verdes',
            'description' => 'Sono apprezzate per il loro sapore fresco e piccante, e rappresentano un piatto delizioso e appagante della cucina messicana.',
            'price' => 12.99,
            'visible' => true,
            'ingredients' => 'Toritllas di Mais, Pollo, Salsa Tomatillo, Formaggio, Panna Acida, Fagioli',
            'image' => 'enchiladas-verdes.jpg',
        ],

            // Restaurant 5
        [
            'restaurant_id' => 5,
            'name' => 'Pizza Margherita del Giardino',
            'description' => 'Classica Pizza Margherita con mozzarella fresca e basilico.',
            'price' => 9.50, 'visible' => true,
            'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
            'image' => 'margherita-pizza.jpg'
        ],
        [
            'restaurant_id' => 5,
            'name' => 'Pasta alla Carbonara del Giardino',
            'description' => 'La carbonara è un piatto di pasta cremoso, ricco e pieno di sapore, un classico della cucina romana.',
            'price' => 12.00,
            'visible' => true,
            'ingredients' => 'Spaghetti, Uova, Pecorino Romano, Guanciale, Pepe Nero',
            'image' => 'pasta-carbonara.jpg'
        ],
        [
            'restaurant_id' => 5, 
            'name' => 'Tiramisù del Giardino', 
            'description' => 'Classico dessert Italiano al gusto di caffè.',  
            'price' => 6.50, 'visible' => true, 
            'ingredients' => 'Mascarpone, Caffè Espresso, Savoiardi, Cacao', 
            'image' => 'tiramisu.jpg'
        ],
        [
            'restaurant_id' => 5, 
            'name' => 'Gnocchi del Giardino', 
            'description' => 'Gli gnocchi di patate sono un piatto tradizionale italiano costituito da piccole palline di impasto di patate, farina e uova.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Patate, Farina, Uova, Salvia, Burro', 
            'image' => 'gnocchi.jpg'
        ],
        [
            'restaurant_id' => 5, 
            'name' => 'Panna Cotta del Giardino', 
            'description' => 'È un dolce elegante e delicato, amato per la sua semplicità e il suo gusto delizioso.', 
            'price' => 7.00, 
            'visible' => true, 
            'ingredients' => 'Panna Liquida, Zucchero, Vaniglia, Gelatina in fogli', 
            'image' => 'panna-cotta.jpg',
        ],
        [
            'restaurant_id' => 5, 
            'name' => 'Rogan Josh del Giardino', 
            'description' => 'Amato per il suo sapore ricco e avvolgente, nonché per il suo profumo invitante.',
            'price' => 14.50, 
            'visible' => true,
            'ingredients' => 'Agnello, Yogurt, Aglio, Zenzero, Garam Masala', 
            'image' => 'rogan-josh.jpg'
        ],
        [
            'restaurant_id' => 5, 
            'name' => 'Pane Naan del Giardino', 
            'description' => 'Morbido Pane Indiano cotto nel Tandoor', 
            'price' => 2.95, 
            'visible' => true, 
            'ingredients' => 'Farina, Acqua, Lievito, Yogurt, Burro Chiarificato', 
            'image' => 'naan-bread.jpg'
        ],
        [
            'restaurant_id' => 5,
            'name' => 'Pollo al Burro del Giardino',
            'description' => 'Piatto iconico della cucina indiana, apprezzato per la sua bontà e versatilità.',
            'price' => 15.99,
            'visible' => true,
            'ingredients' => 'Pollo, Pomodori, Panna, Burro, Spezie',
            'image' => 'butter-chicken.jpg',
        ],
        [
            'restaurant_id' => 5,
            'name' => 'Palak Paneer del Giardino',
            'description' => 'Ricco di sapore e molto apprezzato sia dagli amanti della cucina indiana che da chi cerca opzioni vegetariane.',
            'price' => 13.99,
            'visible' => true,
            'ingredients' => 'Paneer, Spinaci, Aglio, Zenzero, Panna',
            'image' => 'palak-paneer.jpg',
        ],
        [
            'restaurant_id' => 5,
            'name' => 'Chana Masala del Giardino',
            'description' => 'Una scelta molto popolare sia per i vegetariani che per chi ama i piatti ricchi di sapore della cucina indiana.',
            'price' => 11.99,
            'visible' => true,
            'ingredients' => 'Ceci, Cipolle, Pomodori, Spezie',
            'image' => 'chana-masala.jpg',
        ],

        // Restaurant 6
        [
            'restaurant_id' => 6, 
            'name' => 'Pollo Kung Pao Dragone Rosso', 
            'description' => ' La combinazione di ingredienti freschi e spezie rende il pollo Kung Pao un piatto molto apprezzato sia in Cina che in molte cucine internazionali.',
            'price' => 8.99,
            'visible' => true, 
            'ingredients' => 'Pollo, Arachidi, Zucchine, Peperoni, Salsa di Soia, Chili', 
            'image' => 'kung-pao-chicken.jpg'
        ],
        [
            'restaurant_id' => 6, 
            'name' => 'Manzo e Broccoli Dragone Rosso', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 6, 
            'name' => 'Involtini Primavera Dragone Rosso', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 6,
            'name' => 'Anatra alla Pechinese Dragone Rosso',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 6,
            'name' => 'Mapo Tofu Dragone Rosso',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],
        [
            'restaurant_id' => 6, 
            'name' => 'Sushi Misto Dragone Rosso', 
            'description' => 'È un piatto apprezzato per la sua freschezza, la sua presentazione artistica e la sua varietà di sapori e texture.', 
            'price' => 15.00, 
            'visible' => true, 
            'ingredients' => 'Salmone, Tonno, Cetriolo, Riso, Alghe', 
            'image' => 'sushi-platter.jpg'
        ],
        [
            'restaurant_id' => 6, 
            'name' => 'Ramen Dragone Rosso', 
            'description' => "Molto popolare e amato in Giappone e in tutto il mondo per la sua ricchezza di sapore, la sua versatilità e la sua capacità di riscaldare il corpo e l'anima.", 
            'price' => 13.50, 
            'visible' => true, 
            'ingredients' => 'Brodo di Maiale, Noodle, Maiale, Uova, Cipollotto', 
            'image' => 'ramen.jpg'
        ],
        [
            'restaurant_id' => 6, 
            'name' => 'Katsu Curry Dragone Rosso', 
            'description' => 'È un piatto apprezzato per la combinazione di croccantezza e sapore ricco della carne impanata e della salsa curry.',
            'price' => 9.75,
            'visible' => true, 
            'ingredients' => 'Pollo, Pane Grattugiato, Curry, Riso', 
            'image' => 'katsu-curry.jpg'
        ],
        [
            'restaurant_id' => 6,
            'name' => 'Zuppa di Miso Dragone Rosso', 
            'description' => 'La zuppa di miso è apprezzata per il suo sapore salato e leggermente dolce, nonché per le sue proprietà nutrienti.', 
            'price' => 4.50, 
            'visible' => true, 
            'ingredients' => 'Pasta di Miso, Alghe, Tofu, Cipollotto', 
            'image' => 'miso-soup.jpg'
        ],
        [
            'restaurant_id' => 6, 
            'name' => 'Pollo Teriyaki Dragone Rosso', 
            'description' => 'Amato per il suo sapore appagante e la sua semplicità di preparazione.', 
            'price' => 9.50, 
            'visible' => true, 
            'ingredients' => 'Pollo, Salsa di Soia, Mirin, Zucchero, Sakè', 
            'image' => 'teriyaki-chicken.jpg',
        ],

        // Restaurant 7
        [
            'restaurant_id' => 7, 
            'name' => 'Pollo Kung Pao della Lanterna', 
            'description' => ' La combinazione di ingredienti freschi e spezie rende il pollo Kung Pao un piatto molto apprezzato sia in Cina che in molte cucine internazionali.',
            'price' => 8.99,
            'visible' => true, 
            'ingredients' => 'Pollo, Arachidi, Zucchine, Peperoni, Salsa di Soia, Chili', 
            'image' => 'kung-pao-chicken.jpg'
        ],
        [
            'restaurant_id' => 7, 
            'name' => 'Manzo e Broccoli della Lanterna', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 7, 
            'name' => 'Involtini Primavera della Lanterna', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 7,
            'name' => 'Anatra alla Pechinese della Lanterna',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 7,
            'name' => 'Mapo Tofu della Lanterna',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],
        [
            'restaurant_id' => 7, 
            'name' => 'Sushi Misto della Lanterna', 
            'description' => 'È un piatto apprezzato per la sua freschezza, la sua presentazione artistica e la sua varietà di sapori e texture.', 
            'price' => 15.00, 
            'visible' => true, 
            'ingredients' => 'Salmone, Tonno, Cetriolo, Riso, Alghe', 
            'image' => 'sushi-platter.jpg'
        ],
        [
            'restaurant_id' => 7, 
            'name' => 'Ramen della Lanterna', 
            'description' => "Molto popolare e amato in Giappone e in tutto il mondo per la sua ricchezza di sapore, la sua versatilità e la sua capacità di riscaldare il corpo e l'anima.", 
            'price' => 13.50, 
            'visible' => true, 
            'ingredients' => 'Brodo di Maiale, Noodle, Maiale, Uova, Cipollotto', 
            'image' => 'ramen.jpg'
        ],
        [
            'restaurant_id' => 7, 
            'name' => 'Katsu Curry della Lanterna', 
            'description' => ' È un piatto apprezzato per la combinazione di croccantezza e sapore ricco della carne impanata e della salsa curry.',
            'price' => 9.75,
            'visible' => true, 
            'ingredients' => 'Pollo, Pane Grattugiato, Curry, Riso', 
            'image' => 'katsu-curry.jpg'
        ],
        [
            'restaurant_id' => 7,
            'name' => 'Zuppa di Miso della Lanterna', 
            'description' => 'La zuppa di miso è apprezzata per il suo sapore salato e leggermente dolce, nonché per le sue proprietà nutrienti.', 
            'price' => 4.50, 
            'visible' => true, 
            'ingredients' => 'Pasta di Miso, Alghe, Tofu, Cipollotto', 
            'image' => 'miso-soup.jpg'
        ],
        [
            'restaurant_id' => 7, 
            'name' => 'Pollo Teriyaki della Lanterna', 
            'description' => 'Amato per il suo sapore appagante e la sua semplicità di preparazione.', 
            'price' => 9.50, 
            'visible' => true, 
            'ingredients' => 'Pollo, Salsa di Soia, Mirin, Zucchero, Sakè', 
            'image' => 'teriyaki-chicken.jpg',
        ],

        // Restaurant 8
        [
            'restaurant_id' => 8, 
            'name' => 'Pollo Kung Pao Imperiale', 
            'description' => ' La combinazione di ingredienti freschi e spezie rende il pollo Kung Pao un piatto molto apprezzato sia in Cina che in molte cucine internazionali.',
            'price' => 8.99,
            'visible' => true, 
            'ingredients' => 'Pollo, Arachidi, Zucchine, Peperoni, Salsa di Soia, Chili', 
            'image' => 'kung-pao-chicken.jpg'
        ],
        [
            'restaurant_id' => 8, 
            'name' => 'Manzo e Broccoli Imperiale', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 8, 
            'name' => 'Involtini Primavera Imperiale', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 8,
            'name' => 'Anatra alla Pechinese Imperiale',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 8,
            'name' => 'Mapo Tofu Imperiale',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],
        [
            'restaurant_id' => 8, 
            'name' => 'Sushi Misto Imperiale', 
            'description' => 'È un piatto apprezzato per la sua freschezza, la sua presentazione artistica e la sua varietà di sapori e texture.', 
            'price' => 15.00, 
            'visible' => true, 
            'ingredients' => 'Salmone, Tonno, Cetriolo, Riso, Alghe', 
            'image' => 'sushi-platter.jpg'
        ],
        [
            'restaurant_id' => 8, 
            'name' => 'Ramen Imperiale', 
            'description' => "Molto popolare e amato in Giappone e in tutto il mondo per la sua ricchezza di sapore, la sua versatilità e la sua capacità di riscaldare il corpo e l'anima.", 
            'price' => 13.50, 
            'visible' => true, 
            'ingredients' => 'Brodo di Maiale, Noodle, Maiale, Uova, Cipollotto', 
            'image' => 'ramen.jpg'
        ],
        [
            'restaurant_id' => 8, 
            'name' => 'Katsu Curry Imperiale', 
            'description' => 'È un piatto apprezzato per la combinazione di croccantezza e sapore ricco della carne impanata e della salsa curry.',
            'price' => 9.75,
            'visible' => true, 
            'ingredients' => 'Pollo, Pane Grattugiato, Curry, Riso', 
            'image' => 'katsu-curry.jpg'
        ],
        [
            'restaurant_id' => 8,
            'name' => 'Zuppa di Miso Imperiale', 
            'description' => 'La zuppa di miso è apprezzata per il suo sapore salato e leggermente dolce, nonché per le sue proprietà nutrienti.', 
            'price' => 4.50, 
            'visible' => true, 
            'ingredients' => 'Pasta di Miso, Alghe, Tofu, Cipollotto', 
            'image' => 'miso-soup.jpg'
        ],
        [
            'restaurant_id' => 8, 
            'name' => 'Pollo Teriyaki Imperiale', 
            'description' => 'Amato per il suo sapore appagante e la sua semplicità di preparazione.', 
            'price' => 9.50, 
            'visible' => true, 
            'ingredients' => 'Pollo, Salsa di Soia, Mirin, Zucchero, Sakè', 
            'image' => 'teriyaki-chicken.jpg',
        ],

        // Restaurant 9
        [
            'restaurant_id' => 9, 
            'name' => 'Rogan Josh Bolliwood', 
            'description' => 'Amato per il suo sapore ricco e avvolgente, nonché per il suo profumo invitante.',
            'price' => 14.50, 
            'visible' => true,
            'ingredients' => 'Agnello, Yogurt, Aglio, Zenzero, Garam Masala', 
            'image' => 'rogan-josh.jpg'
        ],
        [
            'restaurant_id' => 9, 
            'name' => 'Pane Naan Bolliwood', 
            'description' => 'Morbido Pane Indiano cotto nel Tandoor', 
            'price' => 2.95, 
            'visible' => true, 
            'ingredients' => 'Farina, Acqua, Lievito, Yogurt, Burro Chiarificato', 
            'image' => 'naan-bread.jpg'
        ],
        [
            'restaurant_id' => 9,
            'name' => 'Pollo al Burro Bolliwood',
            'description' => 'Piatto iconico della cucina indiana, apprezzato per la sua bontà e versatilità.',
            'price' => 15.99,
            'visible' => true,
            'ingredients' => 'Pollo, Pomodori, Panna, Burro, Spezie',
            'image' => 'butter-chicken.jpg',
        ],
        [
            'restaurant_id' => 9,
            'name' => 'Palak Paneer Bolliwood',
            'description' => 'Ricco di sapore e molto apprezzato sia dagli amanti della cucina indiana che da chi cerca opzioni vegetariane.',
            'price' => 13.99,
            'visible' => true,
            'ingredients' => 'Paneer, Spinaci, Aglio, Zenzero, Panna',
            'image' => 'palak-paneer.jpg',
        ],
        [
            'restaurant_id' => 9,
            'name' => 'Chana Masala Bolliwood',
            'description' => 'Una scelta molto popolare sia per i vegetariani che per chi ama i piatti ricchi di sapore della cucina indiana.',
            'price' => 11.99,
            'visible' => true,
            'ingredients' => 'Ceci, Cipolle, Pomodori, Spezie',
            'image' => 'chana-masala.jpg',
        ],
        [
            'restaurant_id' => 9,
            'name' => 'Pizza Margherita Bolliwood',
            'description' => 'Classica Pizza Margherita con mozzarella fresca e basilico.',
            'price' => 9.50, 'visible' => true,
            'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
            'image' => 'margherita-pizza.jpg'
        ],
        [
            'restaurant_id' => 9,
            'name' => 'Pasta alla Carbonara Bolliwood',
            'description' => 'La carbonara è un piatto di pasta cremoso, ricco e pieno di sapore, un classico della cucina romana.',
            'price' => 12.00,
            'visible' => true,
            'ingredients' => 'Spaghetti, Uova, Pecorino Romano, Guanciale, Pepe Nero',
            'image' => 'pasta-carbonara.jpg'
        ],
        [
            'restaurant_id' => 9, 
            'name' => 'Tiramisù Bolliwood', 
            'description' => 'Classico dessert Italiano al gusto di caffè.', 
            'price' => 6.50, 'visible' => true, 
            'ingredients' => 'Mascarpone, Caffè Espresso, Savoiardi, Cacao', 
            'image' => 'tiramisu.jpg'
        ],
        [
            'restaurant_id' => 9, 
            'name' => 'Gnocchi Bolliwood', 
            'description' => 'Gli gnocchi di patate sono un piatto tradizionale italiano costituito da piccole palline di impasto di patate, farina e uova.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Patate, Farina, Uova, Salvia, Burro', 
            'image' => 'gnocchi.jpg'
        ],
        [
            'restaurant_id' => 9, 
            'name' => 'Panna Cotta Bolliwood', 
            'description' => 'È un dolce elegante e delicato, amato per la sua semplicità e il suo gusto delizioso.', 
            'price' => 7.00, 
            'visible' => true, 
            'ingredients' => 'Panna Liquida, Zucchero, Vaniglia, Gelatina in fogli', 
            'image' => 'panna-cotta.jpg',
        ],

        // Restaurant 10
        [
            'restaurant_id' => 10, 
            'name' => 'Rogan Josh Ganges', 
            'description' => 'Amato per il suo sapore ricco e avvolgente, nonché per il suo profumo invitante.',
            'price' => 14.50, 
            'visible' => true,
            'ingredients' => 'Agnello, Yogurt, Aglio, Zenzero, Garam Masala', 
            'image' => 'rogan-josh.jpg'
        ],
        [
            'restaurant_id' => 10, 
            'name' => 'Pane Naan Ganges', 
            'description' => 'Piatto iconico della cucina indiana, apprezzato per la sua bontà e versatilità.',
            'price' => 15.99,
            'visible' => true,
            'ingredients' => 'Pollo, Pomodori, Panna, Burro, Spezie',
            'image' => 'butter-chicken.jpg',
        ],
        [
            'restaurant_id' => 10,
            'name' => 'Pollo al Burro Ganges',
            'description' => 'Tender chicken cooked in a creamy tomato curry sauce.',
            'price' => 15.99,
            'visible' => true,
            'ingredients' => 'Chicken, tomato, cream, butter, spices',
            'image' => 'butter-chicken.jpg',
        ],
        [
            'restaurant_id' => 10,
            'name' => 'Palak Paneer Ganges',
            'description' => 'Ricco di sapore e molto apprezzato sia dagli amanti della cucina indiana che da chi cerca opzioni vegetariane.',
            'price' => 13.99,
            'visible' => true,
            'ingredients' => 'Paneer, Spinaci, Aglio, Zenzero, Panna',
            'image' => 'palak-paneer.jpg',
        ],
        [
            'restaurant_id' => 10,
            'name' => 'Chana Masala Ganges',
            'description' => 'Una scelta molto popolare sia per i vegetariani che per chi ama i piatti ricchi di sapore della cucina indiana.',
            'price' => 11.99,
            'visible' => true,
            'ingredients' => 'Ceci, Cipolle, Pomodori, Spezie',
            'image' => 'chana-masala.jpg',
        ],
        [
            'restaurant_id' => 10, 
            'name' => 'Pollo Kung Pao Ganges', 
            'description' => ' La combinazione di ingredienti freschi e spezie rende il pollo Kung Pao un piatto molto apprezzato sia in Cina che in molte cucine internazionali.',
            'price' => 8.99,
            'visible' => true, 
            'ingredients' => 'Pollo, Arachidi, Zucchine, Peperoni, Salsa di Soia, Chili', 
            'image' => 'kung-pao-chicken.jpg'
        ],
        [
            'restaurant_id' => 10, 
            'name' => 'Manzo e Broccoli Ganges', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 10, 
            'name' => 'Involtini Primavera Ganges', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 10,
            'name' => 'Anatra alla Pechinese Ganges',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 10,
            'name' => 'Mapo Tofu Ganges',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],

      
        // Restaurant 11
        [
            'restaurant_id' => 11, 
            'name' => 'Rogan Josh Tandoori', 
            'description' => 'Amato per il suo sapore ricco e avvolgente, nonché per il suo profumo invitante.',
            'price' => 14.50, 
            'visible' => true,
            'ingredients' => 'Agnello, Yogurt, Aglio, Zenzero, Garam Masala', 
            'image' => 'rogan-josh.jpg'
        ],
        [
            'restaurant_id' => 11, 
            'name' => 'Pane Naan Tandoori', 
            'description' => 'Morbido Pane Indiano cotto nel Tandoor', 
            'price' => 2.95, 
            'visible' => true, 
            'ingredients' => 'Farina, Acqua, Lievito, Yogurt, Burro Chiarificato', 
            'image' => 'naan-bread.jpg'
        ],
        [
            'restaurant_id' => 11,
            'name' => 'Pollo al Burro Tandoori',
            'description' => 'Piatto iconico della cucina indiana, apprezzato per la sua bontà e versatilità.',
            'price' => 15.99,
            'visible' => true,
            'ingredients' => 'Pollo, Pomodori, Panna, Burro, Spezie',
            'image' => 'butter-chicken.jpg',
        ],
        [
            'restaurant_id' => 11,
            'name' => 'Palak Paneer Tandoori',
            'description' => 'Ricco di sapore e molto apprezzato sia dagli amanti della cucina indiana che da chi cerca opzioni vegetariane.',
            'price' => 13.99,
            'visible' => true,
            'ingredients' => 'Paneer, Spinaci, Aglio, Zenzero, Panna',
            'image' => 'palak-paneer.jpg',
        ],
        [
            'restaurant_id' => 11,
            'name' => 'Chana Masala Tandoori',
            'description' => 'Una scelta molto popolare sia per i vegetariani che per chi ama i piatti ricchi di sapore della cucina indiana.',
            'price' => 11.99,
            'visible' => true,
            'ingredients' => 'Ceci, Cipolle, Pomodori, Spezie',
            'image' => 'chana-masala.jpg',
        ],
        [
            'restaurant_id' => 11, 
            'name' => 'Tacos Al Pastor Tandoori', 
            'description' => "È un piatto molto popolare e apprezzato per il suo sapore robusto e piccante, e la sua freschezza grazie all'aggiunta di ananas.", 
            'price' => 9.00, 
            'visible' => true, 
            'ingredients' => 'Maiale, Ananas, Cipolla, Coriandolo, Tortillas di Mais', 
            'image' => 'tacos-al-pastor.jpg'
        ],
        [
            'restaurant_id' => 11, 
            'name' => 'Guacamole Tandoori', 
            'description' => "Noto per il suo sapore cremoso e fresco, derivato dall'avAnatrado, e per la sua versatilità in cucina.", 
            'price' => 6.50, 
            'visible' => true, 
            'ingredients' => 'AvAnatrado, Cipolle, Pomodori, Lime, Coriandolo', 
            'image' => 'guacamole.jpg'
        ],
        [
            'restaurant_id' => 11, 
            'name' => 'Ceviche Tandoori', 
            'description' => ' È un piatto leggero e rinfrescante, perfetto per le giornate calde.', 
            'price' => 12.50, 'visible' => true, 
            'ingredients' => 'Pesce, Lime, Cipolle, Coriandolo, Peperoncino', 
            'image' => 'ceviche.jpg',
        ],
        [
            'restaurant_id' => 11, 
            'name' => 'Fajitas Tandoori', 
            'description' => "Le Fajitas Tandoori offrono un'esplosione di sapori speziati e sono un'opzione deliziosa e unica per un pasto.", 
            'price' => 13.95, 
            'visible' => true, 
            'ingredients' => 'Pollo, Peperoni, Cipolle, Spezie', 
            'image' => 'fajitas.jpg',
        ],
        [
            'restaurant_id' => 11,
            'name' => 'Enchiladas Verdes Tandoori',
            'description' => 'Sono apprezzate per il loro sapore fresco e piccante, e rappresentano un piatto delizioso e appagante della cucina messicana.',
            'price' => 12.99,
            'visible' => true,
            'ingredients' => 'Toritllas di Mais, Pollo, Salsa Tomatillo, Formaggio, Panna Acida, Fagioli',
            'image' => 'enchiladas-verdes.jpg',
        ],

        // Restaurant 12 
        [
            'restaurant_id' => 12, 
            'name' => 'Sushi Misto Tokyo', 
            'description' => 'È un piatto apprezzato per la sua freschezza, la sua presentazione artistica e la sua varietà di sapori e texture.', 
            'price' => 15.00, 
            'visible' => true, 
            'ingredients' => 'Salmone, Tonno, Cetriolo, Riso, Alghe', 
            'image' => 'sushi-platter.jpg'
        ],
        [
            'restaurant_id' => 12, 
            'name' => 'Ramen Tokyo', 
            'description' => "Molto popolare e amato in Giappone e in tutto il mondo per la sua ricchezza di sapore, la sua versatilità e la sua capacità di riscaldare il corpo e l'anima.", 
            'price' => 13.50, 
            'visible' => true, 
            'ingredients' => 'Brodo di Maiale, Noodle, Maiale, Uova, Cipollotto', 
            'image' => 'ramen.jpg'
        ],
        [
            'restaurant_id' => 12, 
            'name' => 'Katsu Curry Tokyo', 
            'description' => 'È un piatto apprezzato per la combinazione di croccantezza e sapore ricco della carne impanata e della salsa curry.',
            'price' => 9.75,
            'visible' => true, 
            'ingredients' => 'Pollo, Pane Grattugiato, Curry, Riso', 
            'image' => 'katsu-curry.jpg'
        ],
        [
            'restaurant_id' => 12,
            'name' => 'Zuppa di Miso Tokyo', 
            'description' => 'La zuppa di miso è apprezzata per il suo sapore salato e leggermente dolce, nonché per le sue proprietà nutrienti.', 
            'price' => 4.50, 
            'visible' => true, 
            'ingredients' => 'Pasta di Miso, Alghe, Tofu, Cipollotto', 
            'image' => 'miso-soup.jpg'
        ],
        [
            'restaurant_id' => 12, 
            'name' => 'Pollo Teriyaki Tokyo', 
            'description' => 'Amato per il suo sapore appagante e la sua semplicità di preparazione.', 
            'price' => 9.50, 
            'visible' => true, 
            'ingredients' => 'Pollo, Salsa di Soia, Mirin, Zucchero, Sakè', 
            'image' => 'teriyaki-chicken.jpg',
        ],
        [
            'restaurant_id' => 12, 
            'name' => 'Pollo Kung Pao Tokyo', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 12, 
            'name' => 'Manzo e Broccoli Tokyo', 
            'description' => 'Stir-fried dish with Manzo e Broccoli in a ginger garlic sauce.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Beef, broccoli, garlic, ginger, soy sauce', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 12, 
            'name' => 'Involtini Primavera Tokyo', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 12,
            'name' => 'Anatra alla Pechinese Tokyo',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 12,
            'name' => 'Mapo Tofu Tokyo',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],

        // Restaurant 13 
        [
            'restaurant_id' => 13, 
            'name' => 'Sushi Misto Zen', 
            'description' => 'È un piatto apprezzato per la sua freschezza, la sua presentazione artistica e la sua varietà di sapori e texture.', 
            'price' => 15.00, 
            'visible' => true, 
            'ingredients' => 'Salmone, Tonno, Cetriolo, Riso, Alghe', 
            'image' => 'sushi-platter.jpg'
        ],
        [
            'restaurant_id' => 13, 
            'name' => 'Ramen Zen', 
            'description' => "Molto popolare e amato in Giappone e in tutto il mondo per la sua ricchezza di sapore, la sua versatilità e la sua capacità di riscaldare il corpo e l'anima.", 
            'price' => 13.50, 
            'visible' => true, 
            'ingredients' => 'Brodo di Maiale, Noodle, Maiale, Uova, Cipollotto', 
            'image' => 'ramen.jpg'
        ],
        [
            'restaurant_id' => 13, 
            'name' => 'Katsu Curry Zen', 
            'description' => 'È un piatto apprezzato per la combinazione di croccantezza e sapore ricco della carne impanata e della salsa curry.',
            'price' => 9.75,
            'visible' => true, 
            'ingredients' => 'Pollo, Pane Grattugiato, Curry, Riso', 
            'image' => 'katsu-curry.jpg'
        ],
        [
            'restaurant_id' => 13,
            'name' => 'Zuppa di Miso Zen', 
            'description' => 'La zuppa di miso è apprezzata per il suo sapore salato e leggermente dolce, nonché per le sue proprietà nutrienti.', 
            'price' => 4.50, 
            'visible' => true, 
            'ingredients' => 'Pasta di Miso, Alghe, Tofu, Cipollotto', 
            'image' => 'miso-soup.jpg'
        ],
        [
            'restaurant_id' => 13, 
            'name' => 'Pollo Teriyaki Zen', 
            'description' => 'Amato per il suo sapore appagante e la sua semplicità di preparazione.', 
            'price' => 9.50, 
            'visible' => true, 
            'ingredients' => 'Pollo, Salsa di Soia, Mirin, Zucchero, Sakè', 
            'image' => 'teriyaki-chicken.jpg',
        ],
        [
            'restaurant_id' => 13, 
            'name' => 'Pollo Kung Pao Zen', 
            'description' => ' La combinazione di ingredienti freschi e spezie rende il pollo Kung Pao un piatto molto apprezzato sia in Cina che in molte cucine internazionali.',
            'price' => 8.99,
            'visible' => true, 
            'ingredients' => 'Pollo, Arachidi, Zucchine, Peperoni, Salsa di Soia, Chili', 
            'image' => 'kung-pao-chicken.jpg'
        ],
        [
            'restaurant_id' => 13, 
            'name' => 'Manzo e Broccoli Zen', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 13, 
            'name' => 'Involtini Primavera Zen', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 13,
            'name' => 'Anatra alla Pechinese Zen',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 13,
            'name' => 'Mapo Tofu Zen',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],

    // Restaurant 14 
        [
            'restaurant_id' => 14, 
            'name' => 'Sushi Misto Fuji', 
            'description' => 'È un piatto apprezzato per la sua freschezza, la sua presentazione artistica e la sua varietà di sapori e texture.', 
            'price' => 15.00, 
            'visible' => true, 
            'ingredients' => 'Salmone, Tonno, Cetriolo, Riso, Alghe', 
            'image' => 'sushi-platter.jpg'
        ],
        [
            'restaurant_id' => 14, 
            'name' => 'Ramen Fuji', 
            'description' => "Molto popolare e amato in Giappone e in tutto il mondo per la sua ricchezza di sapore, la sua versatilità e la sua capacità di riscaldare il corpo e l'anima.", 
            'price' => 13.50, 
            'visible' => true, 
            'ingredients' => 'Brodo di Maiale, Noodle, Maiale, Uova, Cipollotto', 
            'image' => 'ramen.jpg'
        ],
        [
            'restaurant_id' => 14, 
            'name' => 'Katsu Curry Fuji', 
            'description' => 'È un piatto apprezzato per la combinazione di croccantezza e sapore ricco della carne impanata e della salsa curry.',
            'price' => 9.75,
            'visible' => true, 
            'ingredients' => 'Pollo, Pane Grattugiato, Curry, Riso', 
            'image' => 'katsu-curry.jpg'
        ],
        [
            'restaurant_id' => 14,
            'name' => 'Zuppa di Miso Fuji', 
            'description' => 'La zuppa di miso è apprezzata per il suo sapore salato e leggermente dolce, nonché per le sue proprietà nutrienti.', 
            'price' => 4.50, 
            'visible' => true, 
            'ingredients' => 'Pasta di Miso, Alghe, Tofu, Cipollotto', 
            'image' => 'miso-soup.jpg'
        ],
        [
            'restaurant_id' => 14, 
            'name' => 'Pollo Teriyaki Fuji', 
            'description' => 'Amato per il suo sapore appagante e la sua semplicità di preparazione.', 
            'price' => 9.50, 
            'visible' => true, 
            'ingredients' => 'Pollo, Salsa di Soia, Mirin, Zucchero, Sakè', 
            'image' => 'teriyaki-chicken.jpg',
        ],
        [
            'restaurant_id' => 14, 
            'name' => 'Pollo Kung Pao Fuji', 
            'description' => ' La combinazione di ingredienti freschi e spezie rende il pollo Kung Pao un piatto molto apprezzato sia in Cina che in molte cucine internazionali.',
            'price' => 8.99,
            'visible' => true, 
            'ingredients' => 'Pollo, Arachidi, Zucchine, Peperoni, Salsa di Soia, Chili', 
            'image' => 'kung-pao-chicken.jpg'
        ],
        [
            'restaurant_id' => 14, 
            'name' => 'Manzo e Broccoli Fuji', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 14, 
            'name' => 'Involtini Primavera Fuji', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 14,
            'name' => 'Anatra alla Pechinese Fuji',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 14,
            'name' => 'Mapo Tofu Fuji',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],

        // Restaurant 15
        [
            'restaurant_id' => 15, 
            'name' => 'Cheeseburger Golden', 
            'description' => 'Viene apprezzato per il suo sapore succulento, la sua semplicità e la sua versatilità.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Manzo, Formaggio, Lattuga, Pomodoro, Cipolla, Pane', 
            'image' => 'cheeseburger.jpg'
        ],
        [
            'restaurant_id' => 15, 
            'name' => 'BBQ Ribs Golden', 
            'description' => 'Sono un piatto apprezzato per la loro bontà e versatilità, e sono una presenza fissa nei menu dei ristoranti barbecue in tutto il mondo.', 
            'price' => 16.50, 
            'visible' => true, 
            'ingredients' => 'Costolette di Maiale, Salsa BBQ, Patate', 
            'image' => 'bbq-ribs.jpg'
        ],
        [
            'restaurant_id' => 15, 
            'name' => 'Zuppa di Vongole Golden', 
            'description' => 'La Zuppa di Vongole è un piatto ricco e confortante, amato per il suo sapore rustico e avvolgente.', 
            'price' => 8.95, 
            'visible' => true,
            'ingredients' => 'Molluschi, Patate, Cipolle, Sedano, Latte, Bacon', 
            'image' => 'clam-chowder.jpg',
        ],
        [
            'restaurant_id' => 15, 
            'name' => 'Pulled Pork Sandwich Golden', 
            'description' => 'È un piatto apprezzato per la sua ricchezza di sapore e la sua morbidezza.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Spalla di Maiale, Salsa BBQ, Coleslaw, Pane', 
            'image' => 'pulled-pork-sandwich.jpg',
        ],
        [
            'restaurant_id' => 15,
            'name' => 'Patatine Fritte Golden',
            'description' => 'Le patatine fritte sono amate per la loro croccantezza esterna e la morbidezza interna, rendendole un contorno versatile o uno snack da gustare da solo.',
            'price' => 2.99,
            'visible' => true,
            'ingredients' => 'Potate, Sale, Olio Vegetale',
            'image' => 'french-fries.jpg',
        ],
        [
            'restaurant_id' => 15,
            'name' => 'Pizza Margherita Golden',
            'description' => 'Classica Pizza Margherita con mozzarella fresca e basilico.',
            'price' => 9.50, 'visible' => true,
            'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
            'image' => 'margherita-pizza.jpg'
        ],
        [
            'restaurant_id' => 15,
            'name' => 'Pasta alla Carbonara Golden',
            'description' => 'La carbonara è un piatto di pasta cremoso, ricco e pieno di sapore, un classico della cucina romana.',
            'price' => 12.00,
            'visible' => true,
            'ingredients' => 'Spaghetti, Uova, Pecorino Romano, Guanciale, Pepe Nero',
            'image' => 'pasta-carbonara.jpg'
        ],
        [
            'restaurant_id' => 15, 
            'name' => 'Tiramisù Golden', 
            'description' => 'Classico dessert Italiano al gusto di caffè.', 
            'price' => 6.50, 'visible' => true, 
            'ingredients' => 'Mascarpone, Caffè Espresso, Savoiardi, Cacao', 
            'image' => 'tiramisu.jpg'
        ],
        [
            'restaurant_id' => 15, 
            'name' => 'Gnocchi Golden', 
            'description' => 'Gli gnocchi di patate sono un piatto tradizionale italiano costituito da piccole palline di impasto di patate, farina e uova.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Patate, Farina, Uova, Salvia, Burro', 
            'image' => 'gnocchi.jpg'
        ],
        [
            'restaurant_id' => 15, 
            'name' => 'Panna Cotta Golden', 
            'description' => 'È un dolce elegante e delicato, amato per la sua semplicità e il suo gusto delizioso.', 
            'price' => 7.00, 
            'visible' => true, 
            'ingredients' => 'Panna Liquida, Zucchero, Vaniglia, Gelatina in fogli', 
            'image' => 'panna-cotta.jpg',
        ],

        // Restaurant 16
        [
            'restaurant_id' => 16, 
            'name' => 'Cheeseburger Liberty', 
            'description' => 'Viene apprezzato per il suo sapore succulento, la sua semplicità e la sua versatilità.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Manzo, Formaggio, Lattuga, Pomodoro, Cipolla, Pane', 
            'image' => 'cheeseburger.jpg'
        ],
        [
            'restaurant_id' => 16, 
            'name' => 'BBQ Ribs Liberty', 
            'description' => 'Sono un piatto apprezzato per la loro bontà e versatilità, e sono una presenza fissa nei menu dei ristoranti barbecue in tutto il mondo.', 
            'price' => 16.50, 
            'visible' => true, 
            'ingredients' => 'Costolette di Maiale, Salsa BBQ, Patate', 
            'image' => 'bbq-ribs.jpg'
        ],
        [
            'restaurant_id' => 16, 
            'name' => 'Zuppa di Vongole Liberty', 
            'description' => 'La Zuppa di Vongole è un piatto ricco e confortante, amato per il suo sapore rustico e avvolgente.', 
            'price' => 8.95, 
            'visible' => true,
            'ingredients' => 'Molluschi, Patate, Cipolle, Sedano, Latte, Bacon', 
            'image' => 'clam-chowder.jpg',
        ],
        [
            'restaurant_id' => 16, 
            'name' => 'Pulled Pork Sandwich Liberty', 
            'description' => 'È un piatto apprezzato per la sua ricchezza di sapore e la sua morbidezza.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Spalla di Maiale, Salsa BBQ, Coleslaw, Pane', 
            'image' => 'pulled-pork-sandwich.jpg',
        ],
        [
            'restaurant_id' => 16,
            'name' => 'Patatine Fritte Liberty',
            'description' => 'Le patatine fritte sono amate per la loro croccantezza esterna e la morbidezza interna, rendendole un contorno versatile o uno snack da gustare da solo.',
            'price' => 2.99,
            'visible' => true,
            'ingredients' => 'Potate, Sale, Olio Vegetale',
            'image' => 'french-fries.jpg',
        ],
        [
            'restaurant_id' => 16, 
            'name' => 'Pollo Kung Pao Liberty', 
            'description' => ' La combinazione di ingredienti freschi e spezie rende il pollo Kung Pao un piatto molto apprezzato sia in Cina che in molte cucine internazionali.',
            'price' => 8.99,
            'visible' => true, 
            'ingredients' => 'Pollo, Arachidi, Zucchine, Peperoni, Salsa di Soia, Chili', 
            'image' => 'kung-pao-chicken.jpg'
        ],
        [
            'restaurant_id' => 16, 
            'name' => 'Manzo e Broccoli Liberty', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 16, 
            'name' => 'Involtini Primavera Liberty', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 16,
            'name' => 'Anatra alla Pechinese Liberty',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 16,
            'name' => 'Mapo Tofu Liberty',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],

        // Restaurant 17
        [
            'restaurant_id' => 17, 
            'name' => 'Cheeseburger Route 66', 
            'description' => 'Viene apprezzato per il suo sapore succulento, la sua semplicità e la sua versatilità.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Manzo, Formaggio, Lattuga, Pomodoro, Cipolla, Pane', 
            'image' => 'cheeseburger.jpg'
        ],
        [
            'restaurant_id' => 17, 
            'name' => 'BBQ Ribs Route 66', 
            'description' => 'Sono un piatto apprezzato per la loro bontà e versatilità, e sono una presenza fissa nei menu dei ristoranti barbecue in tutto il mondo.', 
            'price' => 16.50, 
            'visible' => true, 
            'ingredients' => 'Costolette di Maiale, Salsa BBQ, Patate', 
            'image' => 'bbq-ribs.jpg'
        ],
        [
            'restaurant_id' => 17, 
            'name' => 'Zuppa di Vongole Route 66', 
            'description' => 'La Zuppa di Vongole è un piatto ricco e confortante, amato per il suo sapore rustico e avvolgente.', 
            'price' => 8.95, 
            'visible' => true,
            'ingredients' => 'Molluschi, Patate, Cipolle, Sedano, Latte, Bacon', 
            'image' => 'clam-chowder.jpg',
        ],
        [
            'restaurant_id' => 17, 
            'name' => 'Pulled Pork Route 66', 
            'description' => 'È un piatto apprezzato per la sua ricchezza di sapore e la sua morbidezza.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Spalla di Maiale, Salsa BBQ, Coleslaw, Pane', 
            'image' => 'pulled-pork-sandwich.jpg',
        ],
        [
            'restaurant_id' => 17,
            'name' => 'Patatine Fritte Route 66',
            'description' => 'Le patatine fritte sono amate per la loro croccantezza esterna e la morbidezza interna, rendendole un contorno versatile o uno snack da gustare da solo.',
            'price' => 2.99,
            'visible' => true,
            'ingredients' => 'Potate, Sale, Olio Vegetale',
            'image' => 'french-fries.jpg',
        ],
        [
            'restaurant_id' => 17, 
            'name' => 'Tacos Al Pastor Route 66', 
            'description' => "È un piatto molto popolare e apprezzato per il suo sapore robusto e piccante, e la sua freschezza grazie all'aggiunta di ananas.", 
            'price' => 9.00, 
            'visible' => true, 
            'ingredients' => 'Maiale, Ananas, Cipolla, Coriandolo, Tortillas di Mais', 
            'image' => 'tacos-al-pastor.jpg'
        ],
        [
            'restaurant_id' => 17, 
            'name' => 'Guacamole Route 66', 
            'description' => "Noto per il suo sapore cremoso e fresco, derivato dall'avAnatrado, e per la sua versatilità in cucina.", 
            'price' => 6.50, 
            'visible' => true, 
            'ingredients' => 'AvAnatrado, Cipolle, Pomodori, Lime, Coriandolo', 
            'image' => 'guacamole.jpg'
        ],
        [
            'restaurant_id' => 17, 
            'name' => 'Ceviche Route 66', 
            'description' => ' È un piatto leggero e rinfrescante, perfetto per le giornate calde.', 
            'price' => 12.50, 'visible' => true, 
            'ingredients' => 'Pesce, Lime, Cipolle, Coriandolo, Peperoncino', 
            'image' => 'ceviche.jpg',
        ],
        [
            'restaurant_id' => 17, 
            'name' => 'Fajitas Route 66', 
            'description' => "Le Fajitas Tandoori offrono un'esplosione di sapori speziati e sono un'opzione deliziosa e unica per un pasto.", 
            'price' => 13.95, 
            'visible' => true, 
            'ingredients' => 'Pollo, Peperoni, Cipolle, Spezie', 
            'image' => 'fajitas.jpg',
        ],
        [
            'restaurant_id' => 17,
            'name' => 'Enchiladas Verdes Route 66',
            'description' => 'Sono apprezzate per il loro sapore fresco e piccante, e rappresentano un piatto delizioso e appagante della cucina messicana.',
            'price' => 12.99,
            'visible' => true,
            'ingredients' => 'Toritllas di Mais, Pollo, Salsa Tomatillo, Formaggio, Panna Acida, Fagioli',
            'image' => 'enchiladas-verdes.jpg',
        ],

        // Restaurant 18
        [
            'restaurant_id' => 18, 
            'name' => 'Tacos Al Pastor Azteca', 
            'description' => "È un piatto molto popolare e apprezzato per il suo sapore robusto e piccante, e la sua freschezza grazie all'aggiunta di ananas.", 
            'price' => 9.00, 
            'visible' => true, 
            'ingredients' => 'Maiale, Ananas, Cipolla, Coriandolo, Tortillas di Mais', 
            'image' => 'tacos-al-pastor.jpg'
        ],
        [
            'restaurant_id' => 18, 
            'name' => 'Guacamole Azteca', 
            'description' => "Noto per il suo sapore cremoso e fresco, derivato dall'avAnatrado, e per la sua versatilità in cucina.", 
            'price' => 6.50, 
            'visible' => true, 
            'ingredients' => 'AvAnatrado, Cipolle, Pomodori, Lime, Coriandolo', 
            'image' => 'guacamole.jpg'
        ],
        [
            'restaurant_id' => 18, 
            'name' => 'Ceviche Azteca', 
            'description' => ' È un piatto leggero e rinfrescante, perfetto per le giornate calde.', 
            'price' => 12.50, 'visible' => true, 
            'ingredients' => 'Pesce, Lime, Cipolle, Coriandolo, Peperoncino', 
            'image' => 'ceviche.jpg',
        ],
        [
            'restaurant_id' => 18, 
            'name' => 'Fajitas Azteca', 
            'description' => "Le Fajitas Tandoori offrono un'esplosione di sapori speziati e sono un'opzione deliziosa e unica per un pasto.", 
            'price' => 13.95, 
            'visible' => true, 
            'ingredients' => 'Pollo, Peperoni, Cipolle, Spezie', 
            'image' => 'fajitas.jpg',
        ],
        [
            'restaurant_id' => 18,
            'name' => 'Enchiladas Verdes Azteca',
            'description' => 'Sono apprezzate per il loro sapore fresco e piccante, e rappresentano un piatto delizioso e appagante della cucina messicana.',
            'price' => 12.99,
            'visible' => true,
            'ingredients' => 'Toritllas di Mais, Pollo, Salsa Tomatillo, Formaggio, Panna Acida, Fagioli',
            'image' => 'enchiladas-verdes.jpg',
        ],
        [
            'restaurant_id' => 18, 
            'name' => 'Sushi Misto Azteca', 
            'description' => 'È un piatto apprezzato per la sua freschezza, la sua presentazione artistica e la sua varietà di sapori e texture.', 
            'price' => 15.00, 
            'visible' => true, 
            'ingredients' => 'Salmone, Tonno, Cetriolo, Riso, Alghe', 
            'image' => 'sushi-platter.jpg'
        ],
        [
            'restaurant_id' => 18, 
            'name' => 'Ramen Azteca', 
            'description' => "Molto popolare e amato in Giappone e in tutto il mondo per la sua ricchezza di sapore, la sua versatilità e la sua capacità di riscaldare il corpo e l'anima.", 
            'price' => 13.50, 
            'visible' => true, 
            'ingredients' => 'Brodo di Maiale, Noodle, Maiale, Uova, Cipollotto', 
            'image' => 'ramen.jpg'
        ],
        [
            'restaurant_id' => 18, 
            'name' => 'Katsu Curry Azteca', 
            'description' => 'È un piatto apprezzato per la combinazione di croccantezza e sapore ricco della carne impanata e della salsa curry.',
            'price' => 9.75,
            'visible' => true, 
            'ingredients' => 'Pollo, Pane Grattugiato, Curry, Riso', 
            'image' => 'katsu-curry.jpg'
        ],
        [
            'restaurant_id' => 18,
            'name' => 'Zuppa di Miso Azteca', 
            'description' => 'La zuppa di miso è apprezzata per il suo sapore salato e leggermente dolce, nonché per le sue proprietà nutrienti.', 
            'price' => 4.50, 
            'visible' => true, 
            'ingredients' => 'Pasta di Miso, Alghe, Tofu, Cipollotto', 
            'image' => 'miso-soup.jpg'
        ],
        [
            'restaurant_id' => 18, 
            'name' => 'Pollo Teriyaki Azteca', 
            'description' => 'Amato per il suo sapore appagante e la sua semplicità di preparazione.', 
            'price' => 9.50, 
            'visible' => true, 
            'ingredients' => 'Pollo, Salsa di Soia, Mirin, Zucchero, Sakè', 
            'image' => 'teriyaki-chicken.jpg',
        ],
        [
            'restaurant_id' => 18, 
            'name' => 'Pollo Kung Pao Azteca', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],

            // Restaurant 19
        [
            'restaurant_id' => 19, 
            'name' => 'Tacos Al Pastor del Sol', 
            'description' => "È un piatto molto popolare e apprezzato per il suo sapore robusto e piccante, e la sua freschezza grazie all'aggiunta di ananas.", 
            'price' => 9.00, 
            'visible' => true, 
            'ingredients' => 'Maiale, Ananas, Cipolla, Coriandolo, Tortillas di Mais', 
            'image' => 'tacos-al-pastor.jpg'
        ],
        [
            'restaurant_id' => 19, 
            'name' => 'Guacamole del Sol', 
            'description' => "Noto per il suo sapore cremoso e fresco, derivato dall'avAnatrado, e per la sua versatilità in cucina.", 
            'price' => 6.50, 
            'visible' => true, 
            'ingredients' => 'AvAnatrado, Cipolle, Pomodori, Lime, Coriandolo', 
            'image' => 'guacamole.jpg'
        ],
        [
            'restaurant_id' => 19, 
            'name' => 'Ceviche del Sol', 
            'description' => ' È un piatto leggero e rinfrescante, perfetto per le giornate calde.', 
            'price' => 12.50, 'visible' => true, 
            'ingredients' => 'Pesce, Lime, Cipolle, Coriandolo, Peperoncino', 
            'image' => 'ceviche.jpg',
        ],
        [
            'restaurant_id' => 19, 
            'name' => 'Fajitas del Sol', 
            'description' => "Le Fajitas Tandoori offrono un'esplosione di sapori speziati e sono un'opzione deliziosa e unica per un pasto.", 
            'price' => 13.95, 
            'visible' => true, 
            'ingredients' => 'Pollo, Peperoni, Cipolle, Spezie', 
            'image' => 'fajitas.jpg',
        ],
        [
            'restaurant_id' => 19,
            'name' => 'Enchiladas Verdes del Sol',
            'description' => 'Sono apprezzate per il loro sapore fresco e piccante, e rappresentano un piatto delizioso e appagante della cucina messicana.',
            'price' => 12.99,
            'visible' => true,
            'ingredients' => 'Toritllas di Mais, Pollo, Salsa Tomatillo, Formaggio, Panna Acida, Fagioli',
            'image' => 'enchiladas-verdes.jpg',
        ],
        [
            'restaurant_id' => 19, 
            'name' => 'Pollo Kung Pao del Sol', 
            'description' => ' La combinazione di ingredienti freschi e spezie rende il pollo Kung Pao un piatto molto apprezzato sia in Cina che in molte cucine internazionali.',
            'price' => 8.99,
            'visible' => true, 
            'ingredients' => 'Pollo, Arachidi, Zucchine, Peperoni, Salsa di Soia, Chili', 
            'image' => 'kung-pao-chicken.jpg'
        ],
        [
            'restaurant_id' => 19, 
            'name' => 'Manzo e Broccoli del Sol', 
            'description' => 'Il contrasto tra la carne succosa e i broccoli croccanti, e per essere un piatto soddisfacente e salutare.', 
            'price' => 10.99, 
            'visible' => true, 
            'ingredients' => 'Manzo, Broccoli, Aglio, Zenzero, Salsa di Soia', 
            'image' => 'beef-and-broccoli.jpg'
        ],
        [
            'restaurant_id' => 19, 
            'name' => 'Involtini Primavera del Sol', 
            'description' => 'Sono un antipasto popolare in molti ristoranti cinesi e asiatici, amati per la loro croccantezza e il loro sapore fresco e delicato.', 
            'price' => 8.25, 'visible' => true, 
            'ingredients' => 'Cavolo, Carote, Peperoni, Pollo', 
            'image' => 'spring-rolls.jpg',
        ],
        [
            'restaurant_id' => 19,
            'name' => 'Anatra alla Pechinese del Sol',
            'description' => "La sua preparazione richiede una tecnica particolare e è considerata un'arte culinaria.",
            'price' => 25.99,
            'visible' => true,
            'ingredients' => 'Anatra, Pancake, Cipolle, Cetriolo, Salsa di Fagioli Dolci',
            'image' => 'peking-duck.jpg',
        ],
        [
            'restaurant_id' => 19,
            'name' => 'Mapo Tofu del Sol',
            'description' => 'Il Mapo Tofu è amato in tutto il mondo per la sua complessità di sapori e la sua caldazza appagante.',
            'price' => 14.99,
            'visible' => true,
            'ingredients' => 'Tofu, Macinato di Carne, Peperoncino del Sichuan, Fagioli Neri fermentati, Olio di Peperoncino',
            'image' => 'mapo-tofu.jpg',
        ],

        // Restaurant 20

        [
            'restaurant_id' => 20, 
            'name' => 'Tacos Al Pastor Cactus', 
            'description' => "È un piatto molto popolare e apprezzato per il suo sapore robusto e piccante, e la sua freschezza grazie all'aggiunta di ananas.", 
            'price' => 9.00, 
            'visible' => true, 
            'ingredients' => 'Maiale, Ananas, Cipolla, Coriandolo, Tortillas di Mais', 
            'image' => 'tacos-al-pastor.jpg'
        ],
        [
            'restaurant_id' => 20, 
            'name' => 'Guacamole Cactus', 
            'description' => "Noto per il suo sapore cremoso e fresco, derivato dall'avAnatrado, e per la sua versatilità in cucina.", 
            'price' => 6.50, 
            'visible' => true, 
            'ingredients' => 'AvAnatrado, Cipolle, Pomodori, Lime, Coriandolo', 
            'image' => 'guacamole.jpg'
        ],
        [
            'restaurant_id' => 20, 
            'name' => 'Ceviche Cactus', 
            'description' => ' È un piatto leggero e rinfrescante, perfetto per le giornate calde.', 
            'price' => 12.50, 'visible' => true, 
            'ingredients' => 'Pesce, Lime, Cipolle, Coriandolo, Peperoncino', 
            'image' => 'ceviche.jpg',
        ],
        [
            'restaurant_id' => 20, 
            'name' => 'Fajitas Cactus', 
            'description' => "Le Fajitas Tandoori offrono un'esplosione di sapori speziati e sono un'opzione deliziosa e unica per un pasto.", 
            'price' => 13.95, 
            'visible' => true, 
            'ingredients' => 'Pollo, Peperoni, Cipolle, Spezie', 
            'image' => 'fajitas.jpg',
        ],
        [
            'restaurant_id' => 20,
            'name' => 'Enchiladas Verdes Cactus',
            'description' => 'Sono apprezzate per il loro sapore fresco e piccante, e rappresentano un piatto delizioso e appagante della cucina messicana.',
            'price' => 12.99,
            'visible' => true,
            'ingredients' => 'Toritllas di Mais, Pollo, Salsa Tomatillo, Formaggio, Panna Acida, Fagioli',
            'image' => 'enchiladas-verdes.jpg',
        ],
        [
            'restaurant_id' => 20,
            'name' => 'Pizza Margherita Cactus',
            'description' => 'Classica Pizza Margherita con mozzarella fresca e basilico.',
            'price' => 9.50, 'visible' => true,
            'ingredients' => 'Pomodoro, Mozzarella, Basilico fresco',
            'image' => 'margherita-pizza.jpg'
        ],
        [
            'restaurant_id' => 20,
            'name' => 'Pasta alla Carbonara Cactus',
            'description' => 'La carbonara è un piatto di pasta cremoso, ricco e pieno di sapore, un classico della cucina romana.',
            'price' => 12.00,
            'visible' => true,
            'ingredients' => 'Spaghetti, Uova, Pecorino Romano, Guanciale, Pepe Nero',
            'image' => 'pasta-carbonara.jpg'
        ],
        [
            'restaurant_id' => 20, 
            'name' => 'Tiramisù Cactus', 
            'description' => 'Classico dessert Italiano al gusto di caffè.', 
            'price' => 6.50, 'visible' => true, 
            'ingredients' => 'Mascarpone, Caffè Espresso, Savoiardi, Cacao', 
            'image' => 'tiramisu.jpg'
        ],
        [
            'restaurant_id' => 20, 
            'name' => 'Gnocchi Cactus', 
            'description' => 'Gli gnocchi di patate sono un piatto tradizionale italiano costituito da piccole palline di impasto di patate, farina e uova.', 
            'price' => 11.00, 
            'visible' => true, 
            'ingredients' => 'Patate, Farina, Uova, Salvia, Burro', 
            'image' => 'gnocchi.jpg'
        ],
        [
            'restaurant_id' => 20, 
            'name' => 'Panna Cotta Cactus', 
            'description' => 'È un dolce elegante e delicato, amato per la sua semplicità e il suo gusto delizioso.', 
            'price' => 7.00, 
            'visible' => true, 
            'ingredients' => 'Panna Liquida, Zucchero, Vaniglia, Gelatina in fogli', 
            'image' => 'panna-cotta.jpg',
        ],
    ];