<?php

// config/restaurants.php

return [
    [
        'id' => 1,
        'user_id' => 1,
        'activity_name' => 'La Dolce Vita',
        'VAT_number' => 'IT12345678901',
        'address' => 'Via Monte Bianco, 14, 20149 Milano, MI',
        'image' => 'restaurant1.jpg',
        'description' => "Un angolo di paradiso culinario che offre classici della cucina italiana in un'atmosfera accogliente e romantica.",
    ],
    [
        'id' => 2,
        'user_id' => 2,
        'activity_name' => 'Osteria del Borgo',
        'VAT_number' => 'IT98765432109',
        'address' => 'Corso Buenos Aires, 87, 20124 Milano, MI',
        'image' => 'restaurant2.jpg',
        'description' => "Sapori autentici e ricette tradizionali in un'osteria che sa di casa, nel cuore del vecchio borgo milanese.",
    ],
    [
        'id' => 3,
        'user_id' => 3,
        'activity_name' => 'Trattoria Al Gondoliere',
        'VAT_number' => 'IT11223344556',
        'address' => 'Piazza del Duomo, 22, 20122 Milano, MI',
        'image' => 'restaurant3.jpg',
        'description' => "Gusta la vera cucina veneziana in riva al Naviglio, con serenate in sottofondo e un'ampia scelta di vini.",
    ],
    [
        'id' => 4,
        'user_id' => 4,
        'activity_name' => 'Pizzeria Napoletana',
        'VAT_number' => 'IT66554433221',
        'address' => 'Viale Monza, 56, 20127 Milano, MI',
        'image' => 'restaurant4.jpg',
        'description' => "Pizze cotte in forno a legna, ingredienti freschi e impasto lievitato naturalmente: un assaggio di Napoli in città.",
    ],
    [
        'id' => 5,
        'user_id' => 5,
        'activity_name' => 'Il Giardino Toscano',
        'VAT_number' => 'IT99887766554',
        'address' => 'Via Marghera, 33, 20149 Milano, MI',
        'image' => 'restaurant5.jpg',
        'description' => "Piatti ricchi e robusti serviti in un giardino segreto milanese che ricorda la Toscana, una piccola oasi di pace e sapori.",
    ],
    [
        'id' => 6,
        'user_id' => 6,
        'activity_name' => 'Dragone Rosso',
        'VAT_number' => 'IT55667788990',
        'address' => 'Via Paolo Sarpi, 62, 20154 Milano, MI',
        'image' => 'restaurant6.jpg',
        'description' => "Esplora i sapori autentici del Sichuan in un ambiente vivace, dove il piccante regna sovrano.",
    ],
    [
        'id' => 7,
        'user_id' => 7,
        'activity_name' => 'Lanterna di Shangai',
        'VAT_number' => 'IT77665544332',
        'address' => 'Corso Sempione, 104, 20154 Milano, MI',
        'image' => 'restaurant7.jpg',
        'description' => "Specialità dim sum e piatti innovativi in un locale moderno ispirato alla skyline di Shanghai.",
    ],
    [
        'id' => 8,
        'user_id' => 8,
        'activity_name' => 'Giardino Imperiale',
        'VAT_number' => 'IT22334455667',
        'address' => 'Piazza Gae Aulenti, 5, 20124 Milano, MI',
        'image' => 'restaurant8.jpg',
        'description' => "Un viaggio culinario attraverso la Cina imperiale, con piatti raffinati e un servizio impeccabile.",
    ],
    [
        'id' => 9,
        'user_id' => 9,
        'activity_name' => 'Bollywood Bites',
        'VAT_number' => 'IT33445566778',
        'address' => 'Via Tortona, 19, 20144 Milano, MI',
        'image' => 'restaurant9.jpg',
        'description' => "L'energia e il colore di Bollywood animano questo ristorante, dove i piatti tradizionali incontrano il fascino del cinema indiano, creando un'esperienza unica.",
    ],
    [
        'id' => 10,
        'user_id' => 10,
        'activity_name' => 'Ganges Curry House',
        'VAT_number' => 'IT88990077665',
        'address' => 'Viale Certosa, 88, 20155 Milano, MI',
        'image' => 'restaurant10.jpg',
        'description' => "Un viaggio culinario lungo le rive del Gange, dove ogni curry racconta una storia e porta con sé i sapori autentici dell'India.",
    ],
    [
        'id' => 11,
        'user_id' => 11,
        'activity_name' => 'Taj Mahal Tandoori',
        'VAT_number' => 'IT67584930258',
        'address' => 'Corso Venezia, 47, 20121 Milano, MI',
        'image' => 'restaurant11.jpg',
        'description' => "Spezie esotiche e piatti cucinati lentamente nel tandoor, per un'esperienza indiana autentica e memorabile.",
    ],
    [
        'id' => 12,
        'user_id' => 12,
        'activity_name' => 'Tokyo Ramen',
        'VAT_number' => 'IT42876543210',
        'address' => "Piazza Sant'Ambrogio, 12, 20123 Milano, MI",
        'image' => 'restaurant12.jpg',
        'description' => "Scodelle fumanti di ramen ricco e saporito, in un angolo di Tokyo nel cuore di Milano.",
    ],
    [
        'id' => 13,
        'user_id' => 13,
        'activity_name' => 'Zen Teppanyaki',
        'VAT_number' => 'IT53948726354',
        'address' => 'Via Mecenate, 76, 20138 Milano, MI',
        'image' => 'restaurant13.jpg',
        'description' => "Eleganza e maestria alla griglia, in un'esperienza culinaria che soddisfa tutti i sensi.",
    ],
    [
        'id' => 14,
        'user_id' => 14,
        'activity_name' => 'Monte Fuji',
        'VAT_number' => 'IT64029384756',
        'address' => 'Corso di Porta Romana, 120, 20122 Milano, MI',
        'image' => 'restaurant14.jpg',
        'description' =>  "Aromi delicati e piatti kaiseki in un ambiente sereno che ricorda le pendici del Monte Fuji.",
    ],
    [
        'id' => 15,
        'user_id' => 15,
        'activity_name' => 'Golden Gate Grill',
        'VAT_number' => 'IT75294857392',
        'address' => 'Viale della Liberazione, 15, 20124 Milano, MI',
        'image' => 'restaurant15.jpg',
        'description' => "Specialità alla griglia e birre artigianali in un locale ispirato alla vivace San Francisco.",
    ],
    [
        'id' => 16,
        'user_id' => 16,
        'activity_name' => 'Liberty Steakhouse',
        'VAT_number' => 'IT86420759340',
        'address' => 'Piazza Cinque Giornate, 23, 20129 Milano, MI',
        'image' => 'restaurant16.jpg',
        'description' => "Carni pregiate e un'ampia selezione di vini in questo steakhouse che celebra il sogno americano.",
    ],
    [
        'id' => 17,
        'user_id' => 17,
        'activity_name' => 'Route 66 Roadhouse',
        'VAT_number' => 'IT97354086420',
        'address' => 'Via Brera, 5, 20121 Milano, MI',
        'image' => 'restaurant17.jpg',
        'description' => "Un tributo alla leggendaria strada americana, con piatti robusti e musica dal vivo.",
    ],
    [
        'id' => 18,
        'user_id' => 18,
        'activity_name' => 'Azteca Cantina',
        'VAT_number' => 'IT08236459720',
        'address' => 'Corso Como, 10, 20154 Milano, MI',
        'image' => 'restaurant18.jpg',
        'description' => "Colori vivaci e sapori intensi in questo ristorante che porta il meglio della cucina messicana a Milano.",
    ],
    [
        'id' => 19,
        'user_id' => 19,
        'activity_name' => 'Sol de Mexico',
        'VAT_number' => 'IT19347586049',
        'address' => 'Piazza San Babila, 8, 20122 Milano, MI',
        'image' => 'restaurant19.jpg',
        'description' => "Taco, enchilada e margarita in un ambiente solare che richiama le spiagge di Cancun.",
    ],
    [
        'id' => 20,
        'user_id' => 20,
        'activity_name' => 'Cactus Tacos',
        'VAT_number' => 'IT20495867501',
        'address' => 'Viale Abruzzi, 42, 20131 Milano, MI',
        'image' => 'restaurant20.jpg',
        'description' => "Creatività e ingredienti freschi si fondono in ricette tradizionali e innovazioni audaci.",
    ],
];