<?php

// config/restaurants.php

return [
    [
        'user_id' => 1,
        'activity_name' => 'The Italian Kitchen',
        'VAT_number' => 'IT123456789',
        'address' => '1 Pasta Lane, Rome',
        'image' => 'italian-kitchen.jpg',
        'description' => 'Authentic Italian cuisine from the heart of Rome.',
    ],
    [
        'user_id' => 2,
        'activity_name' => 'Sushi Sama',
        'VAT_number' => 'JP123456789',
        'address' => '2 Sashimi Blvd, Tokyo',
        'image' => 'sushi-sama.jpg',
        'description' => 'Fresh sushi and sashimi from master chefs.',
    ],
    [
        'user_id' => 3,
        'activity_name' => 'Curry Corner',
        'VAT_number' => 'IN123456789',
        'address' => '3 Spice Road, Mumbai',
        'image' => 'curry-corner.jpg',
        'description' => 'Spicy and flavorful Indian curries and breads.',
    ],
    [
        'user_id' => 4,
        'activity_name' => 'American Burgers',
        'VAT_number' => 'US123456789',
        'address' => '4 Freedom Drive, New York',
        'image' => 'american-burgers.jpg',
        'description' => 'Juicy burgers and crispy fries for the soul.',
    ],
    [
        'user_id' => 5,
        'activity_name' => 'Beijing Duck House',
        'VAT_number' => 'CN123456789',
        'address' => '5 Duck Alley, Beijing',
        'image' => 'beijing-duck-house.jpg',
        'description' => 'Crispy Peking duck with traditional accompaniments.',
    ],
    [
        'user_id' => 6,
        'activity_name' => 'The Pizza Masters',
        'VAT_number' => '123456789',
        'address' => '123 Pizza Street, Foodville',
        'image' => 'pizzeria-image.jpg',
        'description' => 'Authentic Italian pizza with homemade sauce and dough.',
    ],
    [
        'user_id' => 7,
        'activity_name' => 'Sushi Delight',
        'VAT_number' => '987654321',
        'address' => '9 Sushi Boulevard, Ocean City',
        'image' => 'sushi-restaurant-image.jpg',
        'description' => 'Fresh sushi and sashimi from the best local fish.',
    ],
    [
        'user_id' => 8,
        'activity_name' => 'Delicious Eats',
        'VAT_number' => 'VAT1001',
        'address' => '101 Food Street, Gourmet City',
        'image' => 'delicious-eats.jpg',
        'description' => 'A modern twist on classic dishes.',
    ],
    [
        'user_id' => 9,
        'activity_name' => 'Burger Hub',
        'VAT_number' => 'VAT1002',
        'address' => '202 Burger Road, Fastfood Town',
        'image' => 'burger-hub.jpg',
        'description' => 'Home of the gourmet burger.',
    ],
    [
        'user_id' => 10,
        'activity_name' => 'Sushi Dreams',
        'VAT_number' => 'VAT1020',
        'address' => '120 Sushi Way, Seaside Village',
        'image' => 'sushi-dreams.jpg',
        'description' => 'Traditional and innovative sushi creations.',
    ],
    [
        'user_id' => 11,
        'activity_name' => 'Sushi Zen',
        'VAT_number' => 'JP987654321',
        'address' => '11 Tranquil Path, Kyoto',
        'image' => 'sushi-zen.jpg',
        'description' => 'Minimalist sushi setting with a focus on zen flavors.',
    ],
    [
        'user_id' => 12,
        'activity_name' => 'Tacos Fiesta',
        'VAT_number' => 'MX987654321',
        'address' => '12 Salsa Street, Mexico City',
        'image' => 'tacos-fiesta.jpg',
        'description' => 'Traditional Mexican tacos with a variety of fillings.',
    ],
    [
        'user_id' => 13,
        'activity_name' => 'BBQ Smokehouse',
        'VAT_number' => 'US123987654',
        'address' => '13 Rib Road, Texas',
        'image' => 'bbq-smokehouse.jpg',
        'description' => 'Smoky, savory BBQ meats slow-cooked to perfection.',
    ],
    [
        'user_id' => 14,
        'activity_name' => 'Dragon Noodles',
        'VAT_number' => 'CN321654987',
        'address' => '14 Noodle Lane, Shanghai',
        'image' => 'dragon-noodles.jpg',
        'description' => 'Hearty bowls of noodle soup with fresh, vibrant toppings.',
    ],
    [
        'user_id' => 15,
        'activity_name' => 'Greek Gyros',
        'VAT_number' => 'GR123456700',
        'address' => '15 Olympus St, Athens',
        'image' => 'greek-gyros.jpg',
        'description' => 'Authentic Greek gyros with tzatziki and fresh vegetables.',
    ],
    [
        'user_id' => 16,
        'activity_name' => 'Tapas Bar',
        'VAT_number' => 'ES123456789',
        'address' => '16 Fiesta Road, Barcelona',
        'image' => 'tapas-bar.jpg',
        'description' => 'Small plates bursting with the flavors of Spain.',
    ],
    [
       'user_id' => 17,
        'activity_name' => 'Vegan Delights',
       'VAT_number' => 'VEG1234567',
        'address' => '17 Green Leaf Blvd, Portland',
        'image' => 'vegan-delights.jpg',
        'description' => 'Innovative plant-based dishes for a sustainable future.',
    ],
    [
        'user_id' => 18,
        'activity_name' => 'Steak House',
        'VAT_number' => 'US765432109',
        'address' => '18 Carnivore Ave, Kansas City',
        'image' => 'steak-house.jpg',
        'description' => 'Premium cuts and fine wines for a classic dining experience.',
    ],
    [
        'user_id' => 19,
        'activity_name' => 'Soul Food Cafe',
        'VAT_number' => 'US987654321',
        'address' => '19 Comfort St, New Orleans',
        'image' => 'soul-food-cafe.jpg',
        'description' => 'Hearty soul food that feels like a warm hug.',
    ],
    [
        'user_id' => 20,
        'activity_name' => 'Parisian Bistro',
        'VAT_number' => 'FR123456789',
        'address' => '20 La Rue, Paris',
        'image' => 'parisian-bistro.jpg',
        'description' => 'Cozy bistro with classic French pastries and coffee.',
    ],
];